# permissions for end users to view backgrounds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: background-viewer-role
rules:
- apiGroups:
  - cluster.engula.io
  resources:
  - backgrounds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - backgrounds/status
  verbs:
  - get
