# permissions for end users to edit engines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: engine-editor-role
rules:
- apiGroups:
  - cluster.engula.io
  resources:
  - engines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - engines/status
  verbs:
  - get
