# permissions for end users to view engulaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: engulacluster-viewer-role
rules:
- apiGroups:
  - cluster.engula.io
  resources:
  - engulaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - engulaclusters/status
  verbs:
  - get
