# permissions for end users to view journals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: journal-viewer-role
rules:
- apiGroups:
  - cluster.engula.io
  resources:
  - journals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - journals/status
  verbs:
  - get
