# permissions for end users to edit journals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: journal-editor-role
rules:
- apiGroups:
  - cluster.engula.io
  resources:
  - journals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - journals/status
  verbs:
  - get
