# permissions for end users to edit kernels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kernel-editor-role
rules:
- apiGroups:
  - cluster.engula.io
  resources:
  - kernels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - kernels/status
  verbs:
  - get
