
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - get
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - backgrounds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - backgrounds/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - backgrounds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - engines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - engines/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - engines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - journals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - journals/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - journals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - kernels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - kernels/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - kernels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - storages/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.engula.io
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - watch
