# permissions for end users to edit storages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-editor-role
rules:
- apiGroups:
  - cluster.engula.io
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.engula.io
  resources:
  - storages/status
  verbs:
  - get
